stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "$AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$CI_COMMIT_REF_SLUG"

before_script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_REGION_NAME
  - aws ecr get-login-password --region $AWS_REGION_NAME | docker login --username AWS --password-stdin $AWS_ECR_REGISTRY

build:
  stage: build
  script:
    - docker-compose build
    - docker tag aws_ecommerce_app:latest $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE
  only:
    - main

deploy:
  stage: deploy
  image: amazon/aws-cli
  script:
    - aws ecs update-service --cluster $AWS_ECS_CLUSTER --service $AWS_ECS_SERVICE --force-new-deployment
  only:
    - main

default:
  tags:
    - docker
